### ISSUE TITLE
 Could not find function "insert_bottom"

### ISSUE THREAD

**Issue by Simple53** [junjunlab/transPlotR#8]
I encountered a problem when combine plots:
```
> bw %>% insert_bottom(gs,height =1)
Error in insert_bottom(., gs, height = 1) : 
  could not find function "insert_bottom"
```
Does this function not included in the trackPlotR？How could I use it? Thanks!

**Comment by junjunlab** [comment]
Please install **aplot** package and load it.

**Comment by Simple53** [comment]
I have solved the problem. Thanks!
